---
title: "trying to make a mao"
author: "Joseph Kilgallen"
date: "2/21/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(shiny)
library(tidyverse)
library(here)
library(bslib)
library(ggplot2)
library(shinythemes)
library(readxl)
library(magrittr)
library(rvest)
library(dplyr)
library(httr)
library(maps)
library(reshape2)
library(ggiraph)
library(RColorBrewer)
library(leaflet)
library(magrittr)
library(sf)
library(rvest)
library(tidyr)
library(maptools)
library(rgdal)
library(rworldmap)
library(sp)
library(plotly)
library(lubridate)
library(rAmCharts)
library(rsconnect)
library(shinydashboard)
library(DT)
library(rnaturalearth)
library(sp)

# Read in the data
gender_data <- read_xlsx(here("data", "Gender.xlsx"))


# # Tidying the data
gender_mod <- gender_data %>%
  rename("HDI Rank" = ...1,
         "Country" = ...2,
         "Gender Equality Index '18" = ...3,
         "Rank '18" = ...5,
         "Maternal Mortality Ratio '15" = SDG3.1,
         "Adolescent Birth Rate '15-'20" = SDG3.7,
         "Seats in Parliment '18" = SDG5.5,
         "Secondary Education (F)'10-'18" = SDG4.6,
         "Secondary Education (M)'10-'18" = ...15,
         "Labour Force Participation (F)'18" = ...17,
         "Labour Force Participation (M)'18" = ...19) %>%
  select(-...4,-...6,-...8,-...10,-...12,-...14,-...16,-...18,-...20) %>%
  filter(!row_number() %in% c(1, 2, 3, 4, 5, 228:261))

```


### Making reactive data table
```{r}
## Creating a subset of the data to use to make the table
tab_data <- gender_mod %>% 
  janitor::clean_names()
## dropping rows that do not contain countries
tab_data <- tab_data %>% slice(-c(193, 200:222))
## need to drop some more--- 
tab_data <- tab_data %>% slice(-c(63, 118, 156))
## now putting in alphabetical order
tab_data <- tab_data %>% arrange(country)

### NEED TO CLEAN UP TABLE
# Interactive Data Table
tab_data_table <- tab_data %>%
  group_by(country, gender_equality_index_18) 

tab_data_table$Status <- NULL
```

## making interactive map
```{r}
## MAKING INTERACTIVE MAP
## creating a subset of the data to use to make a map
map_data <- gender_mod %>% 
  janitor::clean_names()
## dropping rows that do not contain countries
map_data <- map_data %>% slice(-c(193, 200:222))
## need to drop some more--- 
map_data <- map_data %>% slice(-c(63, 118, 156))
## now putting in alphabetical order
map_data <- map_data %>% arrange(country) 

## using rnatural earth to make an interactive map, hopefully
map <- ne_countries()
names(map)[names(map) == "iso_a3"] <- "ISO3"
names(map)[names(map) == "name"] <- "country"

head(map)

# base plot of map
plot(map)

map_merged <- merge(x = map, y = map_data, by = "country", all.x = TRUE)

class(map_merged)

map_merged$gender_equality_index_18 <- as.numeric(map_merged$gender_equality_index_18)

  
## trying to create map with leaflet
  
## first going to make a palette based on the GE index
pal <- colorBin(
  palette = "viridis", domain = map_merged$gender_equality_index_18,
  bins = seq(0, max(map_merged$gender_equality_index_18, na.rm = TRUE) + .1, by = .1)
)

map_merged$labels <- paste0(
  "<strong> Country: </strong> ",
  map_merged$country, "<br/> ",
  "<strong> Gender Equality Index: </strong> ",
  map_merged$gender_equality_index_18, "<br/> "
) %>%
  lapply(htmltools::HTML)

leaflet(map_merged) %>%
  addTiles() %>%
  setView(lng = 0, lat = 30, zoom = 2) %>%
  addPolygons(
    fillColor = ~ pal(gender_equality_index_18),
    color = "white",
    fillOpacity = 0.7,
    label = ~labels,
    highlight = highlightOptions(
      color = "black",
      bringToFront = TRUE
    )
  ) %>%
  leaflet::addLegend(
    pal = pal, values = ~gender_equality_index_18,
    opacity = 0.7, title = "Gender Equality Index"
  )


```












### useful old code
```{r}
## attempt at interactive map using ggplot
# map1 <- ggplot(basemap1, aes(x = long, y = lat, group = group)) +
#   geom_polygon(aes(fill = gender_equality_index_18), color = "black")
# 
# map2 <- map1 + 
#   theme(axis.text.x = element_blank(),
#         axis.text.y = element_blank(),
#         axis.title.x = element_blank(),
#         axis.title.y = element_blank(),
#         legend.position = "none")
# map2
```


